kumuluzee:
  datasources:
    - jndi-name: jdbc/showcase
      connection-url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      connection-url: jdbc:h2:~/h2/showcase;AUTO_SERVER=TRUE
      username: showcase
      password: showcase
      pool:
        max-size: 20