kumuluzee:
  datasources:
    - jndi-name: jdbc/showcase
      connection-url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      connection-url: jdbc:h2:~/h2/showcase;AUTO_SERVER=TRUE
      username: showcase
      password: showcase
      pool:
        max-size: 20
  logs:
    config-file: '<Configuration status="warn">
                    <Appenders>
                      <Console name="STDOUT">
                        <PatternLayout pattern="%d{HH:mm:ss,SSS} %-5p [%c] (%t) %m%n" />
                      </Console>
                    </Appenders>
                    <Loggers>
                      <Root level="warn">
                        <AppenderRef ref="STDOUT" />
                      </Root>
                      <Logger name="de.gedoplan" level="debug" />
                      <Logger name="de.gedoplan.baselibs" level="info" />
                      <Logger name="EeApplication" level="info" />
                    </Loggers>
                  </Configuration>'