kumuluzee:
  openapi:
    enabled: false
  datasources:
    - jndi-name: jdbc/showcase
      connection-url: jdbc:h2:~/h2/showcase;AUTO_SERVER=TRUE
      username: showcase
      password: showcase
      pool:
        max-size: 20